sudo: false
language: python
env:
  global:
    - DATABASE_NAME="travis_ci"
    - DATABASE_USER="postgres"
    - DATABASE_PORT=5432
    - DATABASE_HOST=""
    - DATABASE_PASSWORD=""
    - DJANGO_SETTINGS_MODULE="project.settings"
    - SECRET_KEY="sadfjasasdfasdfsadfsadfsadfeq"

  matrix:
    - DJANGO_VERSION="Django==3.2"
python:
  - "3.7"
  - "3.8"
  - "3.9"
#  - "3.10"
install:
  - pip install poetry
  - cd example
  - poetry install
  - poetry run pip install -q $DJANGO_VERSION
before_script:
  - poetry run black --check .
  - poetry run black --check ../import_export_celery
script:
  - poetry run python3 manage.py test
after_script:
  - coveralls
addons:
  postgresql: "9.6"
matrix:
   allow_failures:
      - env: DJANGO_VERSION='https://github.com/django/django/archive/master.tar.gz'
